"""upgrade table

Revision ID: 7d150c70647e
Revises: b4d688c4f1cf
Create Date: 2025-01-11 01:39:58.921695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d150c70647e"
down_revision: Union[str, None] = "b4d688c4f1cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "is_active", sa.Boolean(), server_default="True", nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_active", sa.Boolean(), server_default="True", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    op.drop_column("tasks", "is_active")
    # ### end Alembic commands ###
